import type { SdrPilotInput, SdrProspectingMode } from "./sdr-pilot.js";
import type { SearchRegime } from "./types.js";

export type SdrPilotScenario = {
  id: string;
  title: string;
  input: SdrPilotInput;
  expected_mode: SdrProspectingMode;
  expected_primary_regime: SearchRegime;
};

export const SDR_PILOT_SCENARIOS_V0_1: SdrPilotScenario[] = [
  {
    id: "thin-good-fit-list",
    title: "Good-fit accounts but thin list coverage",
    input: {
      org_id: "demo-org",
      seat_id: "seat-west-1",
      execution_scope: "seat",
      surface: "list_building",
      icp_completeness: "medium",
      recent_prospect_yield: "low",
      fit_quality: "high",
      contact_coverage: "low",
      territory_saturation: "medium",
      downstream_capacity: "available",
      active_pipeline_inventory: "low",
      operator_note: "Good-fit accounts exist, but coverage is thin and the seat feels stuck.",
      missing_information: ["title coverage by segment", "regional whitespace outside current list"],
    },
    expected_mode: "hold_and_refine_icp",
    expected_primary_regime: "explore",
  },
  {
    id: "full-pipeline-harvest",
    title: "Healthy inventory with no downstream room",
    input: {
      org_id: "demo-org",
      execution_scope: "org",
      surface: "pipeline_review",
      icp_completeness: "high",
      recent_prospect_yield: "high",
      fit_quality: "high",
      contact_coverage: "medium",
      territory_saturation: "medium",
      downstream_capacity: "full",
      active_pipeline_inventory: "high",
      operator_note: "Plenty of qualified inventory already exists and the team is capacity constrained.",
    },
    expected_mode: "pipeline_harvest",
    expected_primary_regime: "compound",
  },
  {
    id: "high-volume-low-fit",
    title: "Plenty of leads but poor fit",
    input: {
      org_id: "demo-org",
      seat_id: "seat-east-2",
      execution_scope: "seat",
      surface: "territory_segmentation",
      icp_completeness: "high",
      recent_prospect_yield: "high",
      fit_quality: "low",
      contact_coverage: "medium",
      territory_saturation: "high",
      downstream_capacity: "available",
      operator_note: "The rep is getting volume, but the territory feels noisy and misaligned.",
    },
    expected_mode: "territory_refinement",
    expected_primary_regime: "prune",
  },
  {
    id: "good-accounts-poor-contacts",
    title: "Strong account fit but weak contact coverage",
    input: {
      org_id: "demo-org",
      execution_scope: "org",
      surface: "enrichment",
      icp_completeness: "high",
      recent_prospect_yield: "high",
      fit_quality: "high",
      contact_coverage: "low",
      territory_saturation: "low",
      downstream_capacity: "available",
      active_pipeline_inventory: "medium",
      operator_note: "Account quality is good; the missing piece is decision-maker coverage.",
    },
    expected_mode: "enrichment_first",
    expected_primary_regime: "coordinate",
  },
  {
    id: "thin-but-clean-whitespace",
    title: "Low yield despite clean fit and open territory",
    input: {
      org_id: "demo-org",
      seat_id: "seat-south-3",
      execution_scope: "seat",
      surface: "list_building",
      icp_completeness: "high",
      recent_prospect_yield: "low",
      fit_quality: "high",
      contact_coverage: "high",
      territory_saturation: "low",
      downstream_capacity: "available",
      active_pipeline_inventory: "low",
      operator_note: "The seat is not finding enough accounts even though the target profile feels right and whitespace should exist.",
    },
    expected_mode: "broad_discovery",
    expected_primary_regime: "explore",
  },
  {
    id: "good-fit-saturated-titles",
    title: "Fit is strong, but the reachable titles are exhausted",
    input: {
      org_id: "demo-org",
      execution_scope: "org",
      surface: "territory_segmentation",
      icp_completeness: "high",
      recent_prospect_yield: "low",
      fit_quality: "high",
      contact_coverage: "high",
      territory_saturation: "high",
      downstream_capacity: "available",
      active_pipeline_inventory: "medium",
      operator_note: "Accounts still fit, but the current title lane looks exhausted and the territory feels tapped out.",
    },
    expected_mode: "title_expansion",
    expected_primary_regime: "explore",
  },
  {
    id: "contact-gap-with-capacity-crunch",
    title: "Good fit and contact gaps, but no SDR room to absorb new work",
    input: {
      org_id: "demo-org",
      seat_id: "seat-central-2",
      execution_scope: "seat",
      surface: "enrichment",
      icp_completeness: "high",
      recent_prospect_yield: "high",
      fit_quality: "high",
      contact_coverage: "low",
      territory_saturation: "medium",
      downstream_capacity: "full",
      active_pipeline_inventory: "high",
      operator_note: "Contact quality is the bottleneck, but the team is already overfull on active work.",
    },
    expected_mode: "pipeline_harvest",
    expected_primary_regime: "prune",
  },
];
