#!/usr/bin/env bash
set -euo pipefail
# Phase 1 OSS extract (TGA-235): copy allowlisted sources into _oss_export/echelon-adaptive-control/
# for review before a public GitHub repo exists. Does not publish npm.

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEST="$ROOT/_oss_export/echelon-adaptive-control"
SRC="$ROOT/src/cognitive-router"
SPEC="$ROOT/docs/cognitive-router/spec"
FIX="$ROOT/fixtures/echelon"

rm -rf "$DEST"
mkdir -p "$DEST/src/cognitive-router" "$DEST/fixtures/echelon" "$DEST/docs/cognitive-router/spec" "$DEST/scripts"

FILES=(
  types.ts
  scoring.ts
  benchmarks.ts
  evaluator.ts
  trace.ts
  debugging-world.ts
  baselines.ts
  router-runner.ts
  benchmark-runner.ts
  replay-dataset.ts
  replay-evaluator.ts
  community-pack-validation.ts
  media-decision.ts
  media-decision-v2.ts
  media-evaluator.ts
  transition-candidate-metrics.ts
  index.ts
  run-tutorial-replay-v0.1.ts
  run-community-example-replay-v0.1.ts
  run-community-pack-validation-selftest.ts
  run-debugging-v1.ts
)

for f in "${FILES[@]}"; do
  cp "$SRC/$f" "$DEST/src/cognitive-router/$f"
done

cp -R "$SPEC/." "$DEST/docs/cognitive-router/spec/"
cp "$FIX/tutorial-replay-v0.1.visible.json" "$DEST/fixtures/echelon/"
cp "$FIX/tutorial-replay-v0.1.evaluator.json" "$DEST/fixtures/echelon/"
cp "$FIX/community-example-v0.1.visible.json" "$DEST/fixtures/echelon/"
cp "$FIX/community-example-v0.1.evaluator.json" "$DEST/fixtures/echelon/"

cp "$ROOT/scripts/verify-echelon-oss-boundary.sh" "$DEST/scripts/"
chmod +x "$DEST/scripts/verify-echelon-oss-boundary.sh"

cat > "$DEST/package.json" <<'JSON'
{
  "name": "@echelon/adaptive-control",
  "version": "0.0.0-oss.1",
  "private": true,
  "type": "module",
  "description": "OSS extract from agent-brain (TGA-235) — not published until legal + LICENSE",
  "scripts": {
    "build": "tsc -p tsconfig.json",
    "check": "tsc -p tsconfig.json --noEmit",
    "check:oss-boundary": "bash scripts/verify-echelon-oss-boundary.sh",
    "check:community-pack-spec": "npm run build && node dist/cognitive-router/run-community-pack-validation-selftest.js",
    "eval:replays:tutorial": "npm run build && node dist/cognitive-router/run-tutorial-replay-v0.1.js",
    "eval:replays:community-example": "npm run build && node dist/cognitive-router/run-community-example-replay-v0.1.js",
    "eval:debugging": "npm run build && node dist/cognitive-router/run-debugging-v1.js"
  },
  "devDependencies": {
    "typescript": "^5.9.3"
  }
}
JSON

cat > "$DEST/tsconfig.json" <<'JSON'
{
  "compilerOptions": {
    "target": "ES2022",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "strict": true,
    "declaration": true,
    "outDir": "dist",
    "rootDir": "src",
    "noUncheckedIndexedAccess": true,
    "exactOptionalPropertyTypes": true,
    "skipLibCheck": true
  },
  "include": ["src/**/*.ts"]
}
JSON

cat > "$DEST/README.md" <<'MD'
# @echelon/adaptive-control (OSS extract preview)

Generated by `agent-brain` script `scripts/export-oss-echelon.sh` ([TGA-235](https://youtrack.thegig.agency/issue/TGA-235)).

**Not a published package:** `private: true` until [TGA-240](https://youtrack.thegig.agency/issue/TGA-240) LICENSE + counsel review.

## Verify locally

```bash
cd _oss_export/echelon-adaptive-control
npm install
npm run check
npm run check:oss-boundary
npm run check:community-pack-spec
npm run eval:replays:tutorial
```

## Next

See `project-brain/echelon/oss-public-extract-runbook-v0.1.md` in the `agent-brain` repo — init GitHub repo, add LICENSE, `npm pack` denylist CI, then `npm publish`.
MD

echo "export-oss-echelon: wrote $DEST"
